# Generated by Django 5.1.3 on 2024-11-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.materialcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_data', models.JSONField()),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.materialcategory')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('style', models.JSONField()),
                ('gates', models.CharField(blank=True, max_length=10, null=True)),
                ('total_linear_feet', models.FloatField(blank=True, null=True)),
                ('corner_posts', models.IntegerField(blank=True, null=True)),
                ('end_posts', models.IntegerField(blank=True, null=True)),
                ('line_posts', models.IntegerField(blank=True, null=True)),
                ('material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('drawing', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FenceApp.customer')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
            },
        ),
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fence_type', models.CharField(choices=[('chain_link', 'Chain Link'), ('iron_fence', 'Iron Fence'), ('wood_privacy', 'Wood Privacy')], max_length=20)),
                ('height', models.CharField(choices=[('4', "4'"), ('5', "5'"), ('6', "6'"), ('8', "8'")], max_length=2)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.company')),
            ],
            options={
                'unique_together': {('company', 'fence_type', 'height')},
            },
        ),
        migrations.CreateModel(
            name='OverheadRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0.74, max_digits=4)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.08, max_digits=4)),
                ('waste_factor', models.DecimalField(decimal_places=2, default=1.1, max_digits=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.company')),
            ],
            options={
                'verbose_name_plural': 'Overhead Rates',
                'unique_together': {('company',)},
            },
        ),
    ]
