# Generated by Django 5.0.6 on 2024-11-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FenceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainlinkBarbWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Barb Wire',
                'verbose_name_plural': 'Barb Wires',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkBraceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenceHeight', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtyPerTerminal', models.IntegerField()),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Brace Band',
                'verbose_name_plural': 'Brace Bands',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkConcrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Concrete',
                'verbose_name_plural': 'Concretes',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('WOOD FENCE', 'wood_fence'), ('IRON FENCE', 'iron_fence'), ('CHAINLINK', 'chainlink')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChainlinkHogTie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Hog Tie',
                'verbose_name_plural': 'Hog Ties',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkLinePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenceHeight', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Line Post',
                'verbose_name_plural': 'Line Posts',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkLinePostCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Line Post Cap',
                'verbose_name_plural': 'Line Post Caps',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkMesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenceHeight', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Mesh',
                'verbose_name_plural': 'Meshes',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkTensionBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenceHeight', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtyPerTerminal', models.IntegerField()),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Tension Band',
                'verbose_name_plural': 'Tension Bands',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkTensionBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenceHeight', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tension Bar',
                'verbose_name_plural': 'Tension Bars',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkTensionWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tension Wire',
                'verbose_name_plural': 'Tension Wires',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkTerminalCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Terminal Cap',
                'verbose_name_plural': 'Terminal Caps',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkTerminalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenceHeight', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Terminal Post',
                'verbose_name_plural': 'Terminal Posts',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkTopRail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Top Rail',
                'verbose_name_plural': 'Top Rails',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkTopRailEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'Top Rail End',
                'verbose_name_plural': 'Top Rail Ends',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkTrussBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=10)),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Truss Bar',
                'verbose_name_plural': 'Truss Bars',
            },
        ),
        migrations.CreateModel(
            name='IronFenceBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Bracket',
                'verbose_name_plural': 'Brackets',
            },
        ),
        migrations.CreateModel(
            name='IronFenceGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fenceHeight', models.DecimalField(decimal_places=0, max_digits=3)),
                ('railCount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Gate',
                'verbose_name_plural': 'Gates',
            },
        ),
        migrations.CreateModel(
            name='IronFenceGateHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Gate Hardware',
                'verbose_name_plural': 'Gate Hardware',
            },
        ),
        migrations.CreateModel(
            name='IronFencePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fenceHeight', models.DecimalField(decimal_places=0, max_digits=3)),
                ('railCount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Panel',
                'verbose_name_plural': 'Panels',
            },
        ),
        migrations.CreateModel(
            name='IronFencePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fenceHeight', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='WoodFenceConcrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku', models.CharField(max_length=10)),
                ('width', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Concrete',
                'verbose_name_plural': 'Concrete',
            },
        ),
        migrations.CreateModel(
            name='WoodFenceFasteners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qty', models.CharField(max_length=10)),
                ('sku', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Fastener',
                'verbose_name_plural': 'Fasteners',
            },
        ),
        migrations.CreateModel(
            name='WoodFenceGates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku', models.CharField(max_length=10)),
                ('width', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fence_height', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Gate',
                'verbose_name_plural': 'Gates',
            },
        ),
        migrations.CreateModel(
            name='WoodFencePickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku', models.CharField(max_length=10)),
                ('width', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fence_height', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Picket',
                'verbose_name_plural': 'Pickets',
            },
        ),
        migrations.CreateModel(
            name='WoodFencePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku', models.CharField(max_length=10)),
                ('fence_height', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='WoodFenceRails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku', models.CharField(max_length=10)),
                ('width', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Rail',
                'verbose_name_plural': 'Rails',
            },
        ),
        migrations.CreateModel(
            name='ChainlinkFence',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FenceApp.material')),
                ('barb_wire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinkbarbwire')),
                ('brace_bands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinkbraceband')),
                ('concrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinkconcrete')),
                ('hog_ties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinkhogtie')),
                ('line_post_caps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinklinepostcap')),
                ('line_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinklinepost')),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinkmesh')),
                ('tension_bands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinktensionband')),
                ('tension_bars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinktensionbar')),
                ('tension_wire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinktensionwire')),
                ('terminal_caps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinkterminalcap')),
                ('terminal_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinkterminalpost')),
                ('top_rail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinktoprail')),
                ('top_rail_ends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinktoprailend')),
                ('truss_bars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainlink_fences', to='FenceApp.chainlinktrussbar')),
            ],
            bases=('FenceApp.material',),
        ),
        migrations.CreateModel(
            name='IronFence',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FenceApp.material')),
                ('brackets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iron_fences', to='FenceApp.ironfencebracket')),
                ('gate_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iron_fences', to='FenceApp.ironfencegatehardware')),
                ('gates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iron_fences', to='FenceApp.ironfencegate')),
                ('panels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iron_fences', to='FenceApp.ironfencepanel')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iron_fences', to='FenceApp.ironfencepost')),
            ],
            bases=('FenceApp.material',),
        ),
        migrations.CreateModel(
            name='WoodFence',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FenceApp.material')),
                ('concrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.woodfenceconcrete')),
                ('fasteners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.woodfencefasteners')),
                ('gates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.woodfencegates')),
                ('pickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.woodfencepickets')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.woodfenceposts')),
                ('rails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FenceApp.woodfencerails')),
            ],
            bases=('FenceApp.material',),
        ),
    ]
