# Generated by Django 5.1.3 on 2024-11-23 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(default='24', on_delete=django.db.models.deletion.CASCADE, to='FenceApp.company'),
            preserve_default=False,
        ),
    ]
