# Generated by Django 5.1.3 on 2024-11-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FenceApp', '0002_remove_material_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborrate',
            name='height',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('8', '8')], max_length=2),
        ),
    ]
